### ISSUE TITLE
Develop nc_genslice

### ISSUE THREAD

**Issue by ocefpaf** [SECOORA/skill_score#5]
For the glider observation comparison we need to have something similar to [`nc_genslice.m`](https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/slicing/nc_genslice.m) from nctoolbox.  It needs #2 to be implemented.

**Comment by ocefpaf** [comment]
@rsignell-usgs Do you have a working example of `nc_genslice.m`?  I am trying to use [load_secoora_models.m](https://github.com/nctoolbox/nctoolbox/blob/master/demos/contrib/load_secoora_models.m), but I am getting:

```matlab
Error using nc_genslice (line 60)
The dimensions of lonTrk, latTrk and timTrk do not match                                                                                                               
                                                                                                                                                                       
Error in load_secoora_models (line 151)                                                                                                                                
    [Tvar,Tdis,Tzed] = nc_genslice(model.url,model.(variable).name,...  
```

**Comment by ocefpaf** [comment]
I need to get this:

![](http://content.screencast.com/users/rsignell/folders/Snagit/media/898e85b9-00c1-4dc8-8d96-701072ee5d19/03.17.2015-06.58.png)

**Comment by rsignell-usgs** [comment]
Yeah, something has changed with SABGOM causing it not to work anymore.   To produce the figure above, I just changed [line 129 on load_secoora_model](https://github.com/nctoolbox/nctoolbox/blob/master/demos/contrib/load_secoora_models.m#L129) to:
```
model_list = {'COAWST', 'USEAST', 'HYCOM'};
```

**Comment by ocefpaf** [comment]
I am getting that for all model.  I think we have different versions or setups.  I just cloned nctoolbox from "https://github.com/nctoolbox/nctoolbox.git" and added the master branch to my Matlab path with `addpath(genpath('./nctoolbox'))`.  Is that OK?

**Comment by rsignell-usgs** [comment]
No,not okay. You need the 1.x branch

On Tuesday, March 17, 2015, Filipe <notifications@github.com> wrote:

> I am getting that for all model. I think we have different versions or
> setups. I just cloned nctoolbox from "
> https://github.com/nctoolbox/nctoolbox.git" and added the master branch
> to my Matlab path with addpath(genpath('./nctoolbox')). Is that OK?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/secoora/issues/5#issuecomment-82285219>.
>


-- 
Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598

**Comment by ocefpaf** [comment]
Got it working!  And here is the first (and probably wrong) python equivalent:

http://nbviewer.ipython.org/gist/ocefpaf/9255e5cea03f7705a5fe

**Comment by rsignell-usgs** [comment]
Cool!  Does it work with dimensionless vertical coordinate models like COAWST?

**Comment by ocefpaf** [comment]
The issue is not the dimensionless coordinate, that loads just fine.  The problem is that iris does not unable perform the any interpolation nor search on 2D coords (X, Y).  I am rolling a version of our own 2D-KDTree for that.

**Comment by ocefpaf** [comment]
@rsignell-usgs I am concerned that the result are wildly different:

http://nbviewer.ipython.org/gist/ocefpaf/64fe42434065dc98c031

 I am using a "nearest" data approach, maybe I should first try to reproduce exactly what `nc_genslice` does...

**Comment by rsignell-usgs** [comment]
@ocefpaf , I was going to look at this more carefully today, but yes "nearest" is *not* going to be okay for this.  We need to use bilinear interpolation.

**Comment by ocefpaf** [comment]
I ran a test with iris interpolation, it is worse actually.  I will try to run it again, but right now I am focusing on make it faster.

**Comment by rsignell-usgs** [comment]
We need to use `bilinear` in lon/lat space, and `linear

**Comment by ocefpaf** [comment]
Yes, that is exactly what iris is doing:

http://scitools.org.uk/iris/docs/v1.7/iris/iris/analysis/interpolate.html#iris.analysis.interpolate.linear

I am running it again now and I'll post the results as soon as they are ready.

**Comment by ocefpaf** [comment]
@rsignell-usgs quick question, is `nc_genslice` extracting a straight line based?  (My Matlab is a little rusty)

https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/slicing/nc_genslice.m#L64-102

BTW iris.analysis.trajectory can add a 3rd dimension and extract a full track:

http://nbviewer.ipython.org/gist/ocefpaf/9255e5cea03f7705a5fe

This is closer to the USEAST figure above, but the data is interpolate along the glider track and not a straight line from start:end.

**Comment by rsignell-usgs** [comment]
@ocefpaf , `nc_genslice` uses straight lines between subsequent x,y locations along the glider path.  We don't worry about z because we pull all the vertical data from the model at each `x,y,t` location (as if the glider was sampling the entire water column instantaneously). 

There is some cleverness here:
https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/slicing/nc_genslice.m#L169-L170
where the fractional `I` and `J` points at the glider locations are determined via interpolation using lon,lat points as scattered input with the integer `I` and `J` values as data.

**Comment by rsignell-usgs** [comment]
@johnwilkin, did I get this right?

**Comment by ocefpaf** [comment]
Thanks! I got that, Iguess my Matlab is not that rusty :wink:

My approach above, using iris, interpolates the data at all the glider track points (lon, lat, time).  That should explain some of the differences we are seeing.  This is my Glider/USEAST track:

![download](https://cloud.githubusercontent.com/assets/950575/6719503/cda1e21a-cd99-11e4-8181-96f944538782.png)

If a glider track is almost a straight line the results will not diverge much, but it can get very different with more convoluted tracks.

**Comment by rsignell-usgs** [comment]
`nc_genslice` also interpolates the data at all the glider track points (lon, lat, time).

**Comment by ocefpaf** [comment]
> nc_genslice uses straight lines between subsequent x,y locations along the glider path.

OK, I misread this part.  I was under the impression that it got only the first and last and created a grid between those points.

**Comment by johnwilkin** [comment]
Rich, yes you are correct that nc_genslice was designed to interpolate to the vector of lon,lat input coordinates (and times if that option is used). So the output should have the dimension (number of vertical levels) x (number of lon/lat points) 

I have since modified my roms_genslice.m to take a Npts optional argument, in which case the lon/lat trajectory is interpolated to Npts evenly distributed in distance increments following the input lon/lat path - kind of like treating the input path as a small set of way points. 

There remain issues with nc_genslice as distributed and the grid_interop features of some data sets, and I've wound back my code to be less elegant but more robust for ROMS curvilinear or rotated grids. 

I also have a slicer that returns velocity normal and perpendicular to the path. But as I've written it it is specific toe OMRS grids - it works directly on the ROMS grid metric (pm,pn) in ROMS i,j space. I'd need to give quite a bit of thought to how to make that generic for CDM data sets.

**Comment by ocefpaf** [comment]
We can do that with iris trajectories. I forgot to close this issue.
